### ISSUE TITLE
首頁-Banner 圖顯示異常

### ISSUE THREAD

**Issue by yoyosoco** [ChiaYiLai/learning#1]
![螢幕快照 2021-06-08 下午2 05 31](https://user-images.githubusercontent.com/5165487/121131744-cc028700-c862-11eb-9b03-d8fc7192b15f.png)
圖片看起來下面被切掉了，應該要像設計稿如下：
![螢幕快照 2021-06-08 下午2 07 27](https://user-images.githubusercontent.com/5165487/121131865-f6544480-c862-11eb-89c0-da32f872fb8f.png)

我想可能是圖片被放大了，應該要左右兩邊縮小來切齊，讓他左右兩邊是留白的
![螢幕快照 2021-06-08 下午2 11 46](https://user-images.githubusercontent.com/5165487/121132245-7aa6c780-c863-11eb-986f-35b5cd15fb0f.png)

**Comment by ChiaYiLai** [comment]
這裡我是用背景放圖，中間文字用打的，banner 區塊要設定各裝置尺寸的高度，因為是滿版，左邊的人腳不容易對齊，我再調整一下高度。不然就要改成放圖片，取代用背景顯示，這樣圖片多高就會 banner 區塊撐多高，不過這種做法，最好把文字放到圖裡

**Comment by yoyosoco** [comment]
那再請調整一下ㄌ
另外圖片用SVG可以嗎？

**Comment by ChiaYiLai** [comment]
那這裡我直接整個banner放 svg 圖片好了，手機版的標題可以幫我放一下嗎？我這裡沒有設定的字體
