### ISSUE TITLE
全站-教育雲 LOGO

### ISSUE THREAD

**Issue by yoyosoco** [ChiaYiLai/learning#11]
![螢幕快照 2021-06-08 下午3 36 16](https://user-images.githubusercontent.com/5165487/121143155-50f39d80-c86f-11eb-92a3-ddcdf9bae976.png)

LOGO 看起來有點模糊，可能要用2x去做，然後設定成點這個 LOGO 也會到首頁

**Comment by ChiaYiLai** [comment]
妳們那裡有大圖或svg嗎？我已經輸出4x了，可能是本來就有點糊

**Comment by yoyosoco** [comment]
沒有⋯那就 let it go  XD

**Comment by yoyosoco** [comment]
@ChiaYiLai 連結還是幫我設定唷！！

**Comment by ChiaYiLai** [comment]
好的，已修正
