### ISSUE TITLE
新增 OG img

### ISSUE THREAD

**Issue by gingerch** [ChiaYiLai/learning#12]
title : 線上教學便利包
meta description:因應新型冠狀病毒疫情之學生居家自主健康管理及防疫期間的學習需求，以及為引導各級學校準備與實施線上教學，教育部邀集有數位教學經驗的教師錄製線上教學概論、線上混成教學實施方式等影音課程；並彙集教育部教育雲及民間數位學習資源、平臺與工具，提供教師數位教學及學生自學參考使用。

![OG img](https://user-images.githubusercontent.com/2968241/121143527-b9427f00-c86f-11eb-95d1-5745abc01a21.png)

**Comment by ChiaYiLai** [comment]
已修正

**Comment by gingerch** [comment]
@ChiaYiLai  圖隨著主視覺更換
<img width="1200" alt="OG img" src="https://user-images.githubusercontent.com/2968241/121321257-84eac380-c940-11eb-9d8b-1c253759fc63.png">

**Comment by gingerch** [comment]
@ChiaYiLai  目前看到 og img 仍是舊圖~

<img width="488" alt="截圖 2021-06-22 下午6 07 54" src="https://user-images.githubusercontent.com/2968241/122906549-db1a2680-d384-11eb-97cc-b61648f6143b.png">

**Comment by ChiaYiLai** [comment]
OG 資料 LINE 要等它更新
