### ISSUE TITLE
全站 - 來源出處：國家教育研究院，新增連結

### ISSUE THREAD

**Issue by gingerch** [ChiaYiLai/learning#15]
@ChiaYiLai  sorry , 這忘記標到。 全站的「國家教育研究院」，新增連結

連結：https://terms.naer.edu.tw/detail/1678790/

![截圖 2021-06-08 下午3 48 58](https://user-images.githubusercontent.com/2968241/121145150-3ae6dc80-c871-11eb-9f0e-51058ab55104.png)

**Comment by ChiaYiLai** [comment]
DeltaMOOCx是由台達基金會、國家教育研究院以及數學、物理、電機電子等學群科中心所共同合作，提供高中職數學、物理、化學、生物、地球科學與電機電子群六大群科2,661部影片。
這裡也要嗎？

**Comment by gingerch** [comment]
sorry , 我發現是不同的，以下列出

國家研究院連結

1. 中小學 - 同步教學模式定義 https://terms.naer.edu.tw/detail/1678790/
2. 中小學 - 非同步教學定義 https://terms.naer.edu.tw/detail/1678802/
3. 中小學 - 混成教學模式 https://terms.naer.edu.tw/detail/1678942/?index=1

大專院校 - 同步教學模式 https://terms.naer.edu.tw/detail/1678790/
大專院校 - 非同步教學模式 https://terms.naer.edu.tw/detail/1678802/
大專院校 - 混成教學模式 https://terms.naer.edu.tw/detail/1678942/?index=1

**Comment by ChiaYiLai** [comment]
大專院校沒有混成教學的說明耶，要加嗎
