### ISSUE TITLE
中小學-混成教學模式 - 定義重複

### ISSUE THREAD

**Issue by gingerch** [ChiaYiLai/learning#16]
![截圖 2021-06-08 下午3 51 45](https://user-images.githubusercontent.com/2968241/121145474-931dde80-c871-11eb-8adb-8cb7b21287c5.png)

混成教學定義：廣義的混成學習則泛指結合應用不同的教學策略 more
混成教學定義：廣義的混成學習則泛指結合應用不同的教學策略、教學方法、教學媒體、教學科技的一種教學模式，涵蓋同步（synchronous）與非同步（asynchronous）學習的一連串學習活動。 (來源出處：國家教育研究院)

**Comment by ChiaYiLai** [comment]
已修正
