### ISSUE TITLE
中小學 - 缺少標題「平台與資源」

### ISSUE THREAD

**Issue by gingerch** [ChiaYiLai/learning#17]
現況
![截圖 2021-06-08 下午3 54 37](https://user-images.githubusercontent.com/2968241/121145925-058ebe80-c872-11eb-897a-a81d8ffa3039.png)

設計稿
<img width="828" alt="截圖 2021-06-08 下午3 55 15" src="https://user-images.githubusercontent.com/2968241/121145989-15a69e00-c872-11eb-9969-b283d46156db.png">

**Comment by ChiaYiLai** [comment]
已修正
