### ISSUE TITLE
首頁-卡片樣式修正

### ISSUE THREAD

**Issue by yoyosoco** [ChiaYiLai/learning#3]
![螢幕快照 2021-06-08 下午2 25 36](https://user-images.githubusercontent.com/5165487/121133890-754a7c80-c865-11eb-8540-d8d9862b7e7e.png)
![螢幕快照 2021-06-08 下午2 26 30](https://user-images.githubusercontent.com/5165487/121134037-8abfa680-c865-11eb-9806-393f1df34bb4.png)
![螢幕快照 2021-06-08 下午2 26 30](https://user-images.githubusercontent.com/5165487/121134053-8c896a00-c865-11eb-9d3d-3883d38f04d5.png)
這些卡片的顯示都應該有圓角，外框線的顏色應該是#D3D3D3。
hover時的效果是整張底色都變成白色的像這樣，並且四周有陰影效果，字體本身並不會改變顏色↓
![螢幕快照 2021-06-08 下午2 27 18](https://user-images.githubusercontent.com/5165487/121134531-15a0a100-c866-11eb-8610-de758146aeaf.png)

**Comment by ChiaYiLai** [comment]
圓角和陰影我再加上去，因為這裡我是跟其他頁的樣式合併，所以共用樣式了，這樣比較整齊，hover 字體變深應該沒關係吧？

**Comment by yoyosoco** [comment]
這個晚點看 ginger 的意思好ㄌ
