### ISSUE TITLE
客服資訊 - 裝飾圖更換

### ISSUE THREAD

**Issue by gingerch** [ChiaYiLai/learning#33]
<img width="408" alt="截圖 2021-06-09 下午4 44 15" src="https://user-images.githubusercontent.com/2968241/121322939-fa0ac880-c941-11eb-9fff-adb963f0baab.png">

<img width="379" alt="Group 429" src="https://user-images.githubusercontent.com/2968241/121323102-1eff3b80-c942-11eb-96aa-ddb6bd645529.png">

**Comment by ChiaYiLai** [comment]
這裡因為左邊的格子拉很長，我把圖片的框線拿掉，比較不會太奇怪
