### ISSUE TITLE
插圖 - 書的截角沒注意到，以下圖片需要更換

### ISSUE THREAD

**Issue by gingerch** [ChiaYiLai/learning#34]
sorry , 眼殘沒注意到書被截角了，以下圖片再請更換

<img width="734" alt="截圖 2021-06-09 下午6 07 40" src="https://user-images.githubusercontent.com/2968241/121336392-0bf26880-c94e-11eb-8dfb-0f49ef354577.png">

<img width="546" alt="截圖 2021-06-09 下午6 11 30" src="https://user-images.githubusercontent.com/2968241/121336500-29273700-c94e-11eb-9b8e-a6a5d05ebdf5.png">

**Comment by ChiaYiLai** [comment]
已更新！
