### ISSUE TITLE
首頁公告 - 移除假資料、更新資料，新增 pdf 

### ISSUE THREAD

**Issue by gingerch** [ChiaYiLai/learning#47]
1. 移除歷史公告假資料。
<img width="1218" alt="截圖 2021-07-01 下午1 37 10" src="https://user-images.githubusercontent.com/2968241/124071217-9cb1f500-da71-11eb-8e8d-094da8853975.png">

2. 將資料更新依序排放

置頂
```
2021.06.28
[線上教學教師增能研習系列課程表 0602-0701](http://srl.ntue.edu.tw/news/20210628%E7%B7%9A%E4%B8%8A%E6%95%99%E5%AD%B8%E6%95%99%E5%B8%AB%E5%A2%9E%E8%83%BD%E7%B3%BB%E5%88%97%E8%AA%B2%E7%A8%8B%E8%A1%A80602-0701.html)

```

第一則

```
2021.06.30
因應疫情教育部業擬定「全國高級中等以下學校學生居家線上學習參考指引」供參考。
```

第二則

<img width="1139" alt="截圖 2021-07-01 下午1 42 15" src="https://user-images.githubusercontent.com/2968241/124071823-88bac300-da72-11eb-8e47-6ffc2957707f.png">

以下為歷史公告

第三則
```
[線上教學教師增能研習系列課程表 0602-0630](http://srl.ntue.edu.tw/news/20210621%E7%B7%9A%E4%B8%8A%E6%95%99%E5%AD%B8%E6%95%99%E5%B8%AB%E5%A2%9E%E8%83%BD%E7%B3%BB%E5%88%97%E8%AA%B2%E7%A8%8B%E8%A1%A80602-0630(0623%E6%9B%B4%E6%96%B0).html)
```

第四則
<img width="802" alt="截圖 2021-07-01 下午1 43 14" src="https://user-images.githubusercontent.com/2968241/124071848-92dcc180-da72-11eb-8ba4-de9fa674689d.png">

**Comment by gingerch** [comment]
關於第一則
```
2021.06.30
因應疫情教育部業擬定「全國高級中等以下學校學生居家線上學習參考指引」供參考。
```
全國高級中等以下學校學生居家線上學習參考指引，需要連到 pdf
想問，目前架構，是有資料夾，可以連到 pdf 嗎？
pdf 位置https://drive.google.com/file/d/1rPCjANq4XmnI9hR8VVuPdoC3plh1zuH4/view?usp=sharing

**Comment by ChiaYiLai** [comment]
可以連pdf的，看要直接連google drive 連結，或是下載放在網站的資料夾？
