### ISSUE TITLE
課程地圖 - 影片科目 - 隱藏

### ISSUE THREAD

**Issue by gingerch** [ChiaYiLai/learning#49]
客戶資料，會有大量的「不分科」。之後會慢慢更新為「英文科」「國文科」現在暫時無法將資料收齊。
想問問這邊能否有個判斷式，只要出現「不分科」時候，在畫面上給予隱藏

<img width="1182" alt="截圖 2021-07-01 下午5 20 10" src="https://user-images.githubusercontent.com/2968241/124100114-c29ac200-da90-11eb-90a6-5f0e62e8fb6e.png">
<img width="1440" alt="截圖 2021-07-01 下午5 21 38" src="https://user-images.githubusercontent.com/2968241/124100238-e231ea80-da90-11eb-93b5-aca9240253d1.png">

**Comment by ChiaYiLai** [comment]
如果不想要英文科出現，就把那邊的h2 tag 註解掉就好囉，等要放的時候再把註解移除

**Comment by gingerch** [comment]
@ChiaYiLai  那可以幫我更新在給小任工程師文件中嗎？感謝！
