### ISSUE TITLE
影片專區 - 客戶無法提供圖片，就保持灰色底

### ISSUE THREAD

**Issue by gingerch** [ChiaYiLai/learning#53]
客戶表示產製影片封面圖片困難。

沒有圖片，就維持灰色底吧

<img width="271" alt="截圖 2021-07-01 下午6 25 42" src="https://user-images.githubusercontent.com/2968241/124115904-eb2ab800-daa0-11eb-8b67-88d9cd743d88.png">

**Comment by ChiaYiLai** [comment]
只要灰色底嗎？還是中間再加播放的icon呢？

**Comment by gingerch** [comment]
不用，我提供過 3 種設計，最後他們大老闆選了灰底 XD

灰地圖
![gray](https://user-images.githubusercontent.com/2968241/124226702-1d3d2800-db3c-11eb-8749-527575e24ed5.png)

**Comment by gingerch** [comment]
更新如下
![gray](https://user-images.githubusercontent.com/2968241/124233715-b1f85380-db45-11eb-951e-75a97f4b2953.png)
