### ISSUE TITLE
課程地圖 - 這些資料尾數還沒有資料，請註解隱藏

### ISSUE THREAD

**Issue by gingerch** [ChiaYiLai/learning#55]
## 基礎課程
非同步教學

<img width="1344" alt="截圖 2021-07-02 下午5 43 45" src="https://user-images.githubusercontent.com/2968241/124255861-373b3280-db5d-11eb-9938-1fb1eff0e5a0.png">

線上混成教學

<img width="1363" alt="截圖 2021-07-02 下午5 45 03" src="https://user-images.githubusercontent.com/2968241/124255927-4ae69900-db5d-11eb-92b5-be6735822dce.png">

## 進階課程
同步教學、非同步教學
<img width="753" alt="截圖 2021-07-02 下午5 45 37" src="https://user-images.githubusercontent.com/2968241/124256065-75385680-db5d-11eb-8236-7f2758ea150e.png">

線上混成教學
<img width="684" alt="截圖 2021-07-02 下午5 47 04" src="https://user-images.githubusercontent.com/2968241/124256154-90a36180-db5d-11eb-937b-25159dc3b3b2.png">

## 行政準備
<img width="751" alt="截圖 2021-07-02 下午5 47 44" src="https://user-images.githubusercontent.com/2968241/124256245-aa44a900-db5d-11eb-9227-84cfcc04a469.png">

**Comment by gingerch** [comment]
這些是假資料，客戶也還沒有確定數量，想建議如何做？
可以隱藏嗎？

**Comment by ChiaYiLai** [comment]
如果目前連一個影片都沒有的項目，可以直接把那個項目註解掉就好～

**Comment by gingerch** [comment]
好的，想先麻煩註解，讓他們大老闆看正確資料🙏

**Comment by gingerch** [comment]
@ChiaYiLai  這裡不是將整個細項註解掉～～是將尾數註解掉～

<img width="1297" alt="截圖 2021-07-05 上午11 50 13" src="https://user-images.githubusercontent.com/2968241/124415420-6a610a00-dd87-11eb-9195-b368f5ebd584.png">

以此為例
<img width="1344" alt="124255861-373b3280-db5d-11eb-9938-1fb1eff0e5a0" src="https://user-images.githubusercontent.com/2968241/124415539-a85e2e00-dd87-11eb-8d76-fe1db3d22166.png">

最後要調整為

![Group 491](https://user-images.githubusercontent.com/2968241/124415556-b3b15980-dd87-11eb-8780-14cfd0f07162.png)
