### ISSUE TITLE
課程地圖 - 影片封面移除

### ISSUE THREAD

**Issue by gingerch** [ChiaYiLai/learning#57]
客戶表示生不出來...影片封面 style 要移除，作為如下：

<img width="752" alt="截圖 2021-07-02 下午6 32 47" src="https://user-images.githubusercontent.com/2968241/124261880-ebd85280-db63-11eb-9c97-64c6855cac49.png">

**Comment by ChiaYiLai** [comment]
所有的影片封面都移除對嗎？

**Comment by gingerch** [comment]
對的，移除吧

**Comment by ChiaYiLai** [comment]
做RWD盡量都不要使用固定寬度或高度，我這邊設定標題顯示3行高～
