### ISSUE TITLE
課程地圖 - 第二張卡片安排在右上方 - 尋求建議

### ISSUE THREAD

**Issue by gingerch** [ChiaYiLai/learning#59]
目前狀況

<img width="1440" alt="截圖 2021-07-05 下午2 21 48" src="https://user-images.githubusercontent.com/2968241/124426307-71dede00-dd9c-11eb-86ff-4a5ae17912ef.png">

客戶希望調整，到右上方

![1625451930750@2x](https://user-images.githubusercontent.com/2968241/124426167-3f34e580-dd9c-11eb-9ffd-893187e930d9.jpeg)

我印象中，RWD 佈局，似乎不能這樣安排。但客戶仍堅持，所以還是來問問，可以做嗎? ˊ ＿＿＿ˋ

**Comment by ChiaYiLai** [comment]
可以的～
