### ISSUE TITLE
大專院校-實施注意事項-設定超連結

### ISSUE THREAD

**Issue by yoyosoco** [ChiaYiLai/learning#6]
![螢幕快照 2021-06-08 下午2 50 28](https://user-images.githubusercontent.com/5165487/121137185-ffe0ab00-c868-11eb-9c65-d72ce372b949.png)

這兩個有超連結的設定：
大專校院採取非現場教學模式保障聽覺障礙學生學習權益具體措施
https://learning.cloud.edu.tw/onlinelearning_file/%E3%80%8C%E5%A4%A7%E5%B0%88%E6%A0%A1%E9%99%A2%E6%8E%A1%E5%8F%96%E9%9D%9E%E7%8F%BE%E5%A0%B4%E6%95%99%E5%AD%B8%E6%A8%A1%E5%BC%8F%E4%BF%9D%E9%9A%9C%E8%81%BD%E8%A6%BA%E9%9A%9C%E7%A4%99%E5%AD%B8%E7%94%9F%E5%AD%B8%E7%BF%92%E6%AC%8A%EF%A8%97%E5%85%B7%E9%AB%94%E6%8E%AA%E6%96%BD%E3%80%8D.pdf

聽損學生接受線上教學參考指引師生版
https://learning.cloud.edu.tw/onlinelearning_file/%E3%80%8C%E8%81%BD%E6%90%8D%E5%AD%B8%E7%94%9F%E6%8E%A5%E5%8F%97%E7%B7%9A%E4%B8%8A%E6%95%99%E5%AD%B8%E5%8F%83%E8%80%83%E6%8C%87%E5%BC%95%E5%B8%AB%E7%94%9F%E7%89%88%E3%80%8D.pdf?v=2.1.4

**Comment by ChiaYiLai** [comment]
已修正
