### ISSUE TITLE
大專院校-混成教學模式-字的校對修正

### ISSUE THREAD

**Issue by yoyosoco** [ChiaYiLai/learning#7]
![螢幕快照 2021-06-08 下午2 57 48](https://user-images.githubusercontent.com/5165487/121138170-04599380-c86a-11eb-8779-30e36bc03e36.png)
【同步教學工具】及 【平臺與資源 】
這邊讓【】也有藍色的超連結

**Comment by ChiaYiLai** [comment]
這裡看要不要全站統一，因為其他地方都是用《》，並且只要有就把括號也加入超連結

**Comment by yoyosoco** [comment]
好~都先統一用《》，而且都加超連結好了
