### ISSUE TITLE
常見問題與客服-項目符號顯示錯誤

### ISSUE THREAD

**Issue by yoyosoco** [ChiaYiLai/learning#9]
![螢幕快照 2021-06-08 下午3 05 40](https://user-images.githubusercontent.com/5165487/121139164-0e2fc680-c86b-11eb-8d10-87c8e36e3b3b.png)

現狀↑ （第一層重複了，第二層沒有顯示）
應該要跟設計稿一樣↓

![螢幕快照 2021-06-08 下午3 05 33](https://user-images.githubusercontent.com/5165487/121139234-20116980-c86b-11eb-8b00-d150aa87260a.png)

**Comment by yoyosoco** [comment]
@ChiaYiLai 還有標題要粗體

**Comment by ChiaYiLai** [comment]
已修正
